package config

const PRICE_MIN_BGN = 3_600
const PRICE_MAX_BGN = 9_000

const NET_REQ_DELAY_MS = 800

const CHAN_BUF_PAGE_WITH_CAR_LINKS = 10
const CHAN_BUF_CAR_LINKS = 100
const CHAN_BUF_CAR_PAGES = 100
const CHAN_BUF_CAR = 100
